const TA_TO_EN = {
  'தமிழ் AI பயண திட்டமிடுபவர்': 'Tamil AI Travel Planner',
  'குரல் மற்றும் உரை அடிப்படையில் செயல்படும் தமிழ் பயண திட்டமிடுபவர்': 'A Tamil-first travel planner powered by text and voice.',
  'உங்கள் பயண திட்டங்களை உரை அல்லது குரல் மூலம் தொடங்குங்கள்': 'Start your travel plans with text or voice.',
  'வணக்கம்,': 'Hi,',
  'வெளியேறு': 'Logout',
  'உள்நுழைக': 'Login',
  'புதிய கணக்கு': 'New Account',
  'சாதாரண எழுத்து': 'Normal Text',
  'பெரிய எழுத்து': 'Large Text',
  'உங்கள் பயணத்தை திட்டமிடுங்கள்': 'Plan Your Trip',
  'பேருந்து': 'Bus',
  'ரயில்': 'Train',
  'விமானம்': 'Flight',
  'தங்கும் விடுதி': 'Hotel',
  'எ.கா: Chennai இருந்து Madurai பயண திட்டம் தேவை': 'e.g. Need a trip plan from Chennai to Madurai',
  'செயலாக்கம்…': 'Processing...',
  'செலுத்து': 'Pay',
  'தேடு': 'Search',
  '— அல்லது குரல் மூலம் —': '- or use voice -',
  'பேசுங்கள் (Record)': 'Speak (Record)',
  'நிறுத்து (Stop)': 'Stop',
  'பதிவு நடக்கிறது…': 'Recording...',
  'Microphone access denied or not available.': 'Microphone access denied or not available.',
  'குரல் பிழை:': 'Voice error:',
  'திட்டம் தயாராகிறது…': 'Preparing your plan...',
  'சமீபத்திய தேடல்கள்': 'Recent Searches',
  'மறை': 'Hide',
  'காட்டு': 'Show',
  'பயண திட்டம்': 'Travel Plan',
  'கேளுங்கள்': 'Listen',
  'பதிவு செய்யுங்கள்': 'Book Now',
  'பயணிகள் எண்ணிக்கை': 'Passengers',
  'நபர்': 'person',
  'நபர்கள்': 'people',
  'பயண தேதி': 'Travel Date',
  'தொலைபேசி எண்': 'Phone Number',
  'மொத்த கட்டணம்': 'Total Fare',
  'உறுதி செய்யுங்கள்': 'Confirm Booking',
  'பதிவு செய்கிறது...': 'Booking...',
  'பதிவு தோல்வியடைந்தது': 'Booking failed',
  'சரியான தொலைபேசி எண்ணை உள்ளிடவும் (10 இலக்கங்கள்)': 'Enter a valid 10-digit phone number',
  'பதிவு எண்': 'Booking ID',
  'PNR எண்': 'PNR',
  'பயணம்': 'Travel',
  'வழித்தடம்': 'Route',
  'பயணிகள்': 'Passengers',
  'தொலைபேசி': 'Phone',
  'கட்டண நிலை': 'Payment Status',
  'பணம் செலுத்துதல் முடிந்தது': 'Payment Completed',
  'பதிவு உருவாக்கப்பட்டது': 'Booking Created',
  'பதிவு ரத்து செய்யப்பட்டது': 'Booking Cancelled',
  'இந்த பதிவை ரத்து செய்ய விரும்புகிறீர்களா?': 'Do you want to cancel this booking?',
  'ரத்து செய்ய இயலவில்லை': 'Could not cancel the booking',
  'பணம் திருப்பி அனுப்பும் செயல்முறை தொடங்கப்பட்டது': 'Refund flow has started',
  'Refund தொடங்க முடியவில்லை': 'Could not start the refund',
  'பணம் செலுத்துதல் தோல்வியடைந்தது': 'Payment failed',
  'பணம் செலுத்துதல் ரத்து செய்யப்பட்டது': 'Payment was cancelled',
  'பணம் செலுத்துதல் வெற்றிகரமாக முடிந்தது! 🎉': 'Payment completed successfully! 🎉',
  'Refund செயல்முறை தொடங்கப்பட்டது': 'Refund flow started',
  'திருப்பி தொகை': 'Refund amount',
  'திருப்பி தொகை இல்லை': 'No refund available',
  'Refund கோரிக்கை அனுப்பப்பட்டுள்ளது. Razorpay நிலையை சரிபார்க்கவும்.': 'Refund has been requested. Check the Razorpay status.',
  'பணம் செலுத்திய பதிவுகளுக்கு மட்டுமே refund செயல்முறை கிடைக்கும்.': 'Refund is available only for paid bookings.',
  'இந்த பதிவு இன்னும் செலுத்தப்படாததால் refund தேவையில்லை.': 'This booking is unpaid, so no refund is needed.',
  'Refund தொடங்கு': 'Start Refund',
  'Refund தொடங்குகிறது...': 'Starting refund...',
  'ரத்து விதிமுறை:': 'Cancellation policy:',
  '• 1 மணி நேரத்திற்குள் — 100% பணம் திருப்பி': '• Within 1 hour - 100% refund',
  '• 1-24 மணி நேரம் — 50% பணம் திருப்பி': '• Within 1-24 hours - 50% refund',
  '• 24 மணி நேரத்திற்கு மேல் — பணம் திருப்பி இல்லை': '• After 24 hours - no refund',
  'ரத்து செய்': 'Cancel Booking',
  'ரத்து செய்கிறது...': 'Cancelling...',
  'நிலுவையில் உள்ளது': 'Pending',
  'செலுத்தப்பட்டது': 'Paid',
  'தோல்வி': 'Failed',
  'திருப்பி அனுப்பப்பட்டது': 'Refunded',
  'பயண தரவுத்தள தேடல் முடிவு': 'Travel database search result',
  'புறப்படும் இடம்:': 'Source:',
  'செல்லும் இடம்:': 'Destination:',
  'தேடல் வகை:': 'Search mode:',
  'அதிகபட்ச கட்டணம்:': 'Max fare:',
  'தயவுசெய்து புறப்படும் இடமும் செல்லும் இடமும் சொல்லுங்கள்.': 'Please provide both source and destination.',
  'பொருந்தும் வழிகள் எதுவும் கிடைக்கவில்லை.': 'No matching routes found.',
  'நகர பெயர்களை மாற்றி மீண்டும் முயற்சிக்கவும்.': 'Try a different city pair.',
  'மொத்த பொருத்தங்கள்:': 'Total matches:',
  'பேருந்து வழிகள்': 'Bus routes',
  'ரயில் வழிகள்': 'Train routes',
  'தங்கும் விடுதி தேடல் முடிவு': 'Hotel search result',
  'நகரம்:': 'City:',
  'மொத்த விடுதிகள்:': 'Total hotels:',
  'தரவுத்தள முடிவுகள்': 'Database Results',
  'பேருந்து தரவுகள்': 'Bus Data',
  'ரயில் தரவுகள்': 'Train Data',
  'தங்கும் விடுதி தரவுகள்': 'Hotel Data',
  'புறப்படும் இடம்': 'Source',
  'செல்லும் இடம்': 'Destination',
  'சேவை வகை': 'Service Type',
  'எண்': 'Number',
  'தூரம்': 'Distance',
  'கட்டணம்': 'Fare',
  'ஏறத்தாழ நேரம்': 'Duration',
  'பதிவு': 'Book',
  'மதிப்பீடு:': 'Rating:',
  'மூடு': 'Close',
  'பதிவு செய்': 'Book',
  'கிமீ': 'km',
  '1 இரவு': '1 night',
  'பயண விருப்பங்கள்': 'Travel Options',
  'வகை': 'Type',
  'பெயர்': 'Name',
  'நேரம்': 'Duration',
  'மின்னஞ்சல்': 'Email',
  'உதாரணம்@email.com': 'example@email.com',
  'கடவுச்சொல்': 'Password',
  'குறைந்தது 6 எழுத்துகள்': 'At least 6 characters',
  'கடவுச்சொல் உறுதிப்படுத்தல்': 'Confirm Password',
  'உள்நுழைவு': 'Login',
  'உங்கள் கணக்கில் உள்நுழையுங்கள்': 'Sign in to your account',
  'கணக்கு இல்லையா?': "Don't have an account?",
  'புதிய கணக்கு உருவாக்கு': 'Create a new account',
  'உங்கள் கணக்கை உருவாக்கி பயண திட்டங்களை தொடங்குங்கள்': 'Create your account and start planning trips.',
  'உங்கள் பயணத்தை இன்றே தொடங்குங்கள்': 'Start your journey today.',
  'தனிப்பட்ட தகவல்': 'Personal Info',
  'பெயர்': 'Name',
  'தொலைபேசி': 'Phone',
  '(விருப்பம்)': '(Optional)',
  'கடவுச்சொற்கள் பொருந்தவில்லை': 'Passwords do not match',
  'கடவுச்சொற்கள் பொருந்துகின்றன': 'Passwords match',
  'பின்': 'Back',
  'கணக்கு உருவாக்கு': 'Create Account',
  'ஏற்கனவே கணக்கு உள்ளதா?': 'Already have an account?',
  'OTP மூலம் கடவுச்சொல் மாற்றம்': 'Reset Password with OTP',
  'தமிழ் AI பயண திட்டமிடுபவரில் உள்நுழைக': 'Sign in to Tamil AI Travel Planner',
  'தமிழ் AI பயண திட்டமிடுபவரில் புதிய கணக்கு உருவாக்குங்கள்': 'Create a new account in Tamil AI Travel Planner',
  'OTP அனுப்பு': 'Send OTP',
  'OTP அனுப்புகிறது…': 'Sending OTP...',
  'அனுப்பிய எண்:': 'Sent to:',
  'புதிய கடவுச்சொல்': 'New Password',
  'புதிய கடவுச்சொல் உறுதிப்படுத்தல்': 'Confirm New Password',
  'புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடவும்': 'Re-enter the new password',
  'கடவுச்சொல்லை மாற்று': 'Reset Password',
  'கடவுச்சொல் மாற்றுகிறது…': 'Resetting password...',
  'கடவுச்சொல்லை மறந்துவிட்டீர்களா?': 'Forgot password?',
  'பாதுகாப்பாக உள்நுழைந்து உங்கள் பயணங்களை தொடருங்கள்': 'Sign in securely and continue your trips.',
  'பதிவு செய்யப்பட்ட தொலைபேசி எண்ணுக்கு Twilio மூலம் OTP அனுப்பப்படும்.': 'An OTP will be sent to your registered phone using Twilio.',
  'உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சல்': 'Your registered email',
  'உங்கள் முழுப் பெயர்': 'Your full name',
  'கடவுச்சொல் மறந்தால் OTP அனுப்ப இந்த எண் பயன்படும்': 'This number will be used for OTP if you forget your password.',
  'அடுத்து': 'Next',
  'பதிவு செய்யப்படுகிறது:': 'Registering:',
  'உங்கள் பயணத்தை இன்றே தொடங்குங்கள்': 'Start your journey today.',
  'உங்கள் கணக்கை உருவாக்கி பயண திட்டங்களை தொடங்குங்கள்': 'Create your account and start planning trips.',
  'உள்நுழைகிறது…': 'Logging in...',
  'சாதாரண': 'Standard',
  'எக்ஸ்பிரஸ்': 'Express',
  'ஏசி ஸ்லீப்பர்': 'AC Sleeper',
  'மல்டி ஆக்ஸில்': 'Multi Axle',
  'சூப்பர்ஃபாஸ்ட்': 'Superfast',
  'பேஸஞ்சர்': 'Passenger',
  'பட்ஜெட்': 'Budget',
  'நடுத்தர': 'Mid-range',
  'சொகுசு': 'Luxury',
  'பாரம்பரியம்': 'Heritage',
  'பிரீமியம்': 'Premium',
  'ரிசார்ட்': 'Resort',
  'ஹோம்ஸ்டே': 'Homestay',
  'மிகவும் பலவீனம்': 'Very Weak',
  'பலவீனம்': 'Weak',
  'சுமார்': 'Okay',
  'நல்லது': 'Good',
  'மிகவும் நல்லது': 'Very Good',
  'ஒரு நாள் திட்டம்:': 'One-day plan:',
  'இனிய பயணம்! 🙏': 'Have a great trip! 🙏',
  'சென்னை': 'Chennai',
  'மதுரை': 'Madurai',
  'கோயம்புத்தூர்': 'Coimbatore',
  'திருச்சி': 'Trichy',
  'சேலம்': 'Salem',
  'ஊட்டி': 'Ooty',
  'பெங்களூர்': 'Bangalore',
  'ஹைதராபாத்': 'Hyderabad',
  'கொச்சி': 'Kochi',
  'மைசூர்': 'Mysore',
  'மங்களூர்': 'Mangalore',
  'புதுச்சேரி': 'Pondicherry',
  'கோவா': 'Goa',
  'பயனர்': 'Traveler',
  'plan_trip': 'trip_plan',
  'find_hotel': 'find_hotel',
  'bus': 'பேருந்து',
  'train': 'ரயில்',
  'flight': 'விமானம்',
  'hotel': 'தங்கும் விடுதி',
  'Bus 🚌': 'பேருந்து 🚌',
  'Train 🚂': 'ரயில் 🚂',
  'Flight ✈️': 'விமானம் ✈️',
  'Hotel 🏨': 'தங்கும் விடுதி 🏨',
  'guest': 'guest',
};

const EN_TO_TA = Object.fromEntries(Object.entries(TA_TO_EN).map(([ta, en]) => [en, ta]));

function replaceAll(text, entries) {
  return entries.reduce((output, [from, to]) => output.split(from).join(to), text);
}

export function translateText(value, language = 'ta') {
  const text = String(value ?? '');
  if (!text) return text;

  if (language === 'en') {
    return replaceAll(text, Object.entries(TA_TO_EN).sort((a, b) => b[0].length - a[0].length));
  }

  return replaceAll(text, Object.entries(EN_TO_TA).sort((a, b) => b[0].length - a[0].length));
}

export function translateMode(mode, language = 'ta') {
  const text = String(mode || '');
  return translateText(text, language);
}

export function getLanguageLabel(language) {
  return language === 'en' ? 'English' : 'தமிழ்';
}
